server:
  port: 8081
spring:
    application:
        name: coffee-display 
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: false
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                show-sql: true
        hibernate:
            naming:
                physical-strategy: com.hyunjina.coffeedisplay.util.UppercaseSnakePhysicalNamingStrategy
            ddl-auto: none
    main:
        allow-bean-definition-overriding: true
        
    cloud:
        stream:
          kafka:
            binder:
              auto-create-topics: false
              brokers: ec2-13-209-5-73.ap-northeast-2.compute.amazonaws.com:9092
        
          function:
            definition: createdOrder
          bindings:
            createdOrder-in-0:
              group: display-service
              destination: order-create
logging:
  level:
    root: info 
    org:
      hibernate:
        type:
          SQL: debug
          descriptor:
            sql:
              BasicBinder: trace
    com:
      hyunjina: debug